baseURL: ""
languageCode: en-us
theme: smigle
title: Zacmando Encyclopedia
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 4
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 5
params:
  abbrDateFmt: "Jan 2"
  author: "ZM"
  brandIconFile: "images/perl-camel.jpg"
  dateFmt: "2006-01-02"
#  customStylesheets: # Use to override theme styles, like logo size
#    - "css/custom.css"
  social:
    - name: GitHub
      url: https://github.com/zacmando
    - name: Instagram
      url: https://instagram.com/zacmando10
    - name: Personal website
      url: https://zacmerhi.com
  subtitle: "An uncurated memory labrinth"

